=== eclipse-mat/mat/plugins/org.eclipse.mat.report/schema/report.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (c) 2011, 2018 IBM Corporation.
    All rights reserved. This program and the accompanying materials
    are made available under the terms of the Eclipse Public License v1.0
    which accompanies this distribution, and is available at
    http://www.eclipse.org/legal/epl-v10.html
   
    Contributors:
        Andrew Johnson - initial API and implementation
 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://www.eclipse.org/mat/report.xsd"
	targetNamespace="http://www.eclipse.org/mat/report.xsd">

	<xs:annotation>
		<xs:documentation>This defines how reports for Eclipse Memory Analyzer should be constructed.</xs:documentation>
	</xs:annotation>
	<xs:element name="param">
		<xs:annotation>
			<xs:documentation>This allows output of a query to be controlled.
			Parameters are substituted in certain elements and attributes when ${keyname} is seen.
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="key" type="paramkey" use="required"></xs:attribute>
			<xs:attribute name="value" type="paramvalue"
				use="required"></xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:simpleType name="paramkey">
		<xs:annotation>
			<xs:documentation>A parameter - either one of a fixed set of known
			types, or anything for an adopter defined type.
			</xs:documentation>
		</xs:annotation>
		<xs:union memberTypes="paramkeyfixed paramkeyany" />
	</xs:simpleType>

	<xs:simpleType name="paramkeyany">
		<xs:annotation>
			<xs:documentation>A general parameter key
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="[A-Za-z0-9_.]+" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="paramkeyfixed">
		<xs:annotation>
			<xs:documentation>The name of a parameter to control a report.
			See org.eclipse.mat.report.Params
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="timestamp" />
			<!--
			<xs:enumeration value="snapshot" />
			<xs:enumeration value="snapshot_prefix" />
			-->

			<xs:enumeration value="format" />
			<xs:enumeration value="filename" />
			<xs:enumeration value="filename_suffix" />

			<xs:enumeration value="html.collapsed" />
			<xs:enumeration value="html.separate_file" />
			<xs:enumeration value="html.is_important" />
			<xs:enumeration value="html.show_table_header" />
			<xs:enumeration value="html.show_heading" />
			<xs:enumeration value="html.show_totals" />
			<xs:enumeration value="html.render_details" />

			<xs:enumeration value="rendering.pattern" />

			<xs:enumeration value="sort_column" />
			<xs:enumeration value="filter" />
			<xs:enumeration value="limit" />
			<xs:enumeration value="hide_column" />

			<xs:enumeration value="derived_data_column" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="paramvalue">
		<xs:annotation>
			<xs:documentation>A value for a parameter - either one of a fixed set of known
			types, or anything as a translatable string.
			</xs:documentation>
		</xs:annotation>
		<xs:union memberTypes="booleanvalue patternvalue formatvalue derived_data_columnvalue decimalstring columnnumber translatablestring" /> 
	</xs:simpleType>

	<xs:simpleType name="booleanvalue">
		<xs:annotation>
			<xs:documentation>Choices for a boolean value.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="true" />
			<xs:enumeration value="false" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="patternvalue">
		<xs:annotation>
			<xs:documentation>Choices for a pattern.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="overview_details" />
			<xs:enumeration value="sequential" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="formatvalue">
		<xs:annotation>
			<xs:documentation>Choices for a format.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="csv" />
			<xs:enumeration value="html" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="derived_data_columnvalue">
		<xs:annotation>
			<xs:documentation>Choices for a pattern.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="_default_=PRECISE" />
			<xs:enumeration value="_default_=APPROXIMATE" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="decimalstring">
		<xs:annotation>
			<xs:documentation>A number as text
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="[1-9][0-9]*" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="columnnumber">
		<xs:annotation>
			<xs:documentation>A number preceded by # as text
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="#[0-9]+" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="translatedstring">
		<xs:annotation>
			<xs:documentation>A string with a leading % to be used as key into
				the plugin properties file to provided translated text.
				Default text to be used for a missing translation can be provided after the key and a space.
			</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:pattern value="%[A-Za-z0-9_.]+( .*)?" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="untranslatedstring">
		<xs:restriction base="xs:string">
			<xs:pattern value="([^%].*)|" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="literalpercentuntranslatedstring">
		<xs:restriction base="xs:string">
			<xs:pattern value="%%.*" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="translatablestring">
		<xs:annotation>
			<xs:documentation>A readable string or a string that will be
				translated according to the plugin.properties file.
			</xs:documentation>
		</xs:annotation>
		<xs:union memberTypes="translatedstring untranslatedstring literalpercentuntranslatedstring" />
	</xs:simpleType>

	<xs:element name="query">
		<xs:annotation>
			<xs:documentation>The gives details for a query to be executed - both the command and any parameters controlling display of the query.
			</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="param" maxOccurs="unbounded" minOccurs="0"></xs:element>
				<xs:element ref="command"></xs:element>
			</xs:sequence>
			<xs:attribute name="name" type="translatablestring" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="template">
		<xs:annotation>
			<xs:documentation>A reference to another report to be run, via plugin id and name.
			</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\w+(.\w)*:\w+"></xs:pattern>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="command">
		<xs:annotation>
			<xs:documentation>
				This specifies a query command to be executed.
				The command can have arguments, and parameter substitution with ${} can be used to inject text.
			</xs:documentation>
		</xs:annotation>
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="\S+(\s+\S+)*"></xs:pattern>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

	<xs:element name="section">
		<xs:annotation>
			<xs:documentation>A whole section of a report, made up of other sections or queries.</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="param" maxOccurs="unbounded" minOccurs="0"></xs:element>
				<xs:choice maxOccurs="unbounded" minOccurs="1">
					<xs:element ref="query">
					</xs:element>
					<xs:element ref="section">
					</xs:element>
					<xs:element ref="template">
					</xs:element>
				</xs:choice>
			</xs:sequence>
			<xs:attribute name="name" type="translatablestring" use="required" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== eclipse-mat/mat/plugins/org.eclipse.mat.api/META-INF/reports/suspects2.xml
<!--
    Copyright (c) 2008, 2020 SAP AG and IBM Corporation.
    All rights reserved. This program and the accompanying materials
    are made available under the terms of the Eclipse Public License v1.0
    which accompanies this distribution, and is available at
    http://www.eclipse.org/legal/epl-v10.html
   
    Contributors:
        SAP AG - initial API and implementation
        Andrew Johnson - comparison queries
 -->
<section name="%suspects2.title" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.eclipse.org/mat/report.xsd"
	xsi:schemaLocation="http://www.eclipse.org/mat/report.xsd platform:/resource/org.eclipse.mat.report/schema/report.xsd">

	<param key="html.collapsed" value="false" />
	<param key="filename_suffix" value="%suspects2.suffix Leak Suspects Delta" />	

	<section name="%overview2.title">
		<param key="html.separate_file" value="true" />
		<template>org.eclipse.mat.api:overview2</template>
	</section>
	
	<query name="%suspects2.leaks">
		<command>leakhunter2 -baseline ${baseline}</command>
	</query>

</section>

=== eclipse-mat/mat/plugins/org.eclipse.mat.tests/META-INF/tests/regression.xml
<!--
    Copyright (c) 2008, 2021 SAP AG and others
    All rights reserved. This program and the accompanying materials
    are made available under the terms of the Eclipse Public License 2.0
    which accompanies this distribution, and is available at
    https://www.eclipse.org/legal/epl-2.0/

    SPDX-License-Identifier: EPL-2.0
   
    Contributors:
        SAP AG - initial implementation
 -->
 <section name="Regression Tests" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.eclipse.org/mat/report.xsd"
	xsi:schemaLocation="http://www.eclipse.org/mat/report.xsd ../../../org.eclipse.mat.report/schema/report.xsd">
	<query name="info">
		<param key="format" value="csv" />
		<param key="filename" value="info.csv" />
		<param key="html.separate_file" value="true" />
		<param key="html.show_table_header" value="false" />
		<command>heap_dump_overview</command>
	</query>
	<query name="System Properties">
		<param key="format" value="csv" />
		<param key="filename" value="System_Properties.csv" />
		<param key="html.separate_file" value="true" />
		<param key="sort_column" value="Key=ASC" />
		<param key="limit" value="1000" />
		<command>system_properties</command>
	</query>
	<query name="Class Histogram">
	    <param key="format" value="csv" />
		<param key="filename" value="Class_Histogram.csv" />
		<param key="html.separate_file" value="true" />
		<param key="sort_column" value="#3=DESC,#2=DESC,#1=DESC,#0" />
		<param key="derived_data_column" value="_default_=APPROXIMATE" />
		<param key="limit" value="50000" />
		<command>histogram</command>
	</query>
	<query name="Class Loader Histogram">
	    <param key="format" value="csv" />
		<param key="filename" value="Class_Loader_Histogram.csv" />
		<param key="html.separate_file" value="true" />
		<param key="sort_column" value="#3=DESC,#2=DESC,#1=DESC,#0" />
		<param key="derived_data_column" value="_default_=APPROXIMATE" />
		<param key="limit" value="50000" />
		<command>histogram -groupBy BY_CLASSLOADER</command>
	</query>
	<query name="Dominator Tree">
		<param key="format" value="csv" />
		<param key="filename" value="Dominator_Tree.csv" />
		<param key="html.separate_file" value="true" />
		<param key="sort_column" value="#2=DESC,#1=DESC,#0" />
		<param key="limit" value="50000" />
		<command>dominator_tree</command>
	</query>
	<query name="Dominator Tree (binary)">
		<command>dom_tree_binary_test</command>
	</query>
	<query name="List 1000 Strings">
		<param key="format" value="csv" />
		<param key="filename" value="List_1000_Strings.csv" />
		<param key="html.separate_file" value="true" />
		<param key="sort_column" value="ADDRESS" />
		<param key="limit" value="1000" />
		<command>oql "select s.@objectAddress as ADDRESS, toString(s)as VALUE from java.lang.String s"</command>
	</query>
	<query name="Paths from GC Roots">
		<param key="format" value="csv" />
		<param key="filename" value="Paths_from_GC_Root.csv" />
		<param key="html.separate_file" value="true" />
		<param key="limit" value="100" />
		<!--  Test sorting by non-existing columns -->
		<param key="sort_column" value="NOT EXIST" />
		<command>path2gc_reg_test</command>
	</query>
	<query name="Merged Paths from GC Roots">
		<param key="filename" value="Merged_Paths_from_GC_Roots.csv" />
		<param key="format" value="csv" />
		<param key="html.separate_file" value="true" />
		<param key="limit" value="1000" />
		<command>merged_paths_reg_test</command>
	</query>
	<query name="Immediate Dominators of java.util.HashMap$Entry">
		<param key="filename" value="Immediate_Dominators_of_java.util.HashMap$Entry.csv" />
		<param key="format" value="csv" />
		<param key="html.separate_file" value="true" />
		<param key="sort_column" value="#4=DESC,#3=DESC,#2=DESC,#1=DESC,#0" />
		<param key="limit" value="1000" />
		<command>immediate_dominators java.util.HashMap$Entry</command>
	</query>
	<query name="Thread Overview">
		<param key="filename" value="Thread_Overview.csv" />
		<param key="format" value="csv" />
		<param key="html.separate_file" value="true" />
		<param key="sort_column" value="Name,Object / Stack Frame" />
		<param key="limit" value="1000" />
		<command>thread_overview</command>
	</query>
</section>

=== eclipse-mat/mat/plugins/org.eclipse.mat.tests/META-INF/tests/performance.xml
<!--
    Copyright (c) 2008, 2021 SAP AG and others
    All rights reserved. This program and the accompanying materials
    are made available under the terms of the Eclipse Public License 2.0
    which accompanies this distribution, and is available at
    https://www.eclipse.org/legal/epl-2.0/

    SPDX-License-Identifier: EPL-2.0
   
    Contributors:
        SAP AG - initial implementation
 -->
 <section name="Performance Tests"  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.eclipse.org/mat/report.xsd"
	xsi:schemaLocation="http://www.eclipse.org/mat/report.xsd ../../../org.eclipse.mat.report/schema/report.xsd">
	<query name="Paths from GC Roots">
		<param key="html.separate_file" value="true" />
		<param key="limit" value="100" />
		<command>path2gc_reg_test</command>
	</query>
	<query name="Merged Paths from GC Roots">
		<param key="html.separate_file" value="true" />
		<param key="limit" value="1000" />
		<command>merged_paths_reg_test</command>
	</query>
	<query name="Retained Size Approx for Histogram">
		<param key="html.separate_file" value="true" />
		<param key="limit" value="50000" />
		<command>retained_size_histogram_test -approx</command>
	</query>
	<query name="Retained Size Approx for Classloaders">
		<param key="html.separate_file" value="true" />
		<param key="limit" value="50000" />
		<command>retained_size_histogram_test -byClassLoader -approx</command>
	</query>
	<query name="Retained Size for Histogram(precise)">
		<param key="html.separate_file" value="true" />
		<param key="limit" value="50000" />
		<command>retained_size_histogram_test</command>
	</query>
	<query name="Retained Size for Classloaders(precise)">
		<param key="html.separate_file" value="true" />
		<param key="limit" value="50000" />
		<command>retained_size_histogram_test -byClassLoader</command>
	</query>
	<query name="Immediate Dominators of java.util.HashMap$Entry">
		<param key="html.separate_file" value="true" />
		<param key="limit" value="1000" />
		<command>immediate_dominators java.util.HashMap$Entry</command>
	</query>
</section>

=== eclipse-mat/mat/plugins/org.eclipse.mat.hprof/reports/exporthprof.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (c) 2018,2022 IBM Corporation.
    All rights reserved. This program and the accompanying materials
    are made available under the terms of the Eclipse Public License 2.0
    which accompanies this distribution, and is available at
    https://www.eclipse.org/legal/epl-2.0/

    SPDX-License-Identifier: EPL-2.0
   
    Contributors:
        Andrew Johnson - initial creation
 -->
<query name="%report.exporthprof.title Export HPROF" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.eclipse.org/mat/report.xsd"
	xsi:schemaLocation="http://www.eclipse.org/mat/report.xsd platform:/resource/org.eclipse.mat.report/schema/report.xsd">

	<param key="output" value=""></param>
	<param key="redact" value="NONE"></param>
	<param key="map" value=""></param>
	<param key="skip" value="java\\..*|boolean|byte|char|short|int|long|float|double|void"></param>
	<param key="avoid" value="%report.exporthprof.defaultavoid .*ae.*|.*oe.*|.*uu.*|.*kr.*|.*kw.*|.*[cC]ie.*|.*[^c]ei.*"></param>
	<param key="options" value=""></param>

	<command>export_hprof -output "${output}" -map "${map}" -redact ${redact} -skip ${skip} -avoid ${avoid} ${options}</command>
</query>

=== eclipse-mat/mat/plugins/org.eclipse.mat.api/META-INF/reports/overview.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (c) 2008, 2018 SAP AG and IBM Corporation.
    All rights reserved. This program and the accompanying materials
    are made available under the terms of the Eclipse Public License v1.0
    which accompanies this distribution, and is available at
    http://www.eclipse.org/legal/epl-v10.html
   
    Contributors:
        SAP AG - initial API and implementation
        Andrew Johnson - add schema
 -->
<section name="%overview.title" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.eclipse.org/mat/report.xsd" xsi:schemaLocation="http://www.eclipse.org/mat/report.xsd platform:/resource/org.eclipse.mat.report/schema/report.xsd">

	<param key="html.collapsed" value="false" />
	<param key="filename_suffix" value="%overview.suffix" />

	<query name="%overview.heap_dump_overview">
		<param key="html.show_table_header" value="false" />
		<command>heap_dump_overview</command>
	</query>
	<query name="%overview.system_properties">
		<param key="html.separate_file" value="true" />
		<param key="sort_column" value="#1=ASC" />
		<param key="hide_column" value="#0" />
		<param key="limit" value="1000" />
		<command>system_properties</command>
	</query>
	<query name="%overview.threads">
		<param key="limit" value="1000" />
		<param key="html.separate_file" value="true" />
		<param key="html.render_details" value="false" />
		<command>thread_overview</command>
	</query>
	<query name="%overview.top_consumers">
		<param key="html.separate_file" value="true" />
		<command>top_consumers_html</command>
	</query>
	<query name="%overview.class_histogram">
		<param key="html.separate_file" value="true" />
		<param key="sort_column" value="#3" />
		<param key="derived_data_column" value="_default_=APPROXIMATE" />
		<command>histogram</command>
	</query>
</section>

=== eclipse-mat/mat/plugins/org.eclipse.mat.javaee/META-INF/reports/javaee-overview.xml
<section name="Enterprise Java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.eclipse.org/mat/report.xsd"
        xsi:schemaLocation="http://www.eclipse.org/mat/report.xsd ../../../org.eclipse.mat.report/schema/report.xsd"
        >
    <!-- 
    <param key="html.collapsed" value="false" />
    <param key="filename_suffix" value="%suspects.suffix" />

    <section name="%overview.title">
            <param key="html.separate_file" value="true" />
            <template>org.eclipse.mat.api:overview</template>
    </section>
 -->
    <query name="HTTP Sessions">
        <command>javaee-http-sessions</command>
    </query>
    <query name="HTTP Session attributes">
        <command>javaee-http-session-attributes</command>
    </query>
    <query name="HTTP Requests">
        <command>javaee-http-requests</command>
    </query>
    <query name="Servlets">
        <command>javaee-servlets</command>
    </query>
    <query name="Stateful EJBs">
        <command>javaee-ejb-stateful</command>
    </query>
    <query name="Stateless EJBs">
        <command>javaee-ejb-less</command>
    </query>
</section>

=== eclipse-mat/mat/plugins/org.eclipse.mat.api/META-INF/reports/suspects.xml
<!--
    Copyright (c) 2008, 2018 SAP AG and IBM Corporation.
    All rights reserved. This program and the accompanying materials
    are made available under the terms of the Eclipse Public License v1.0
    which accompanies this distribution, and is available at
    http://www.eclipse.org/legal/epl-v10.html
   
    Contributors:
        SAP AG - initial API and implementation
        Andrew Johnson - add schema
 -->
<section name="%suspects.title" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.eclipse.org/mat/report.xsd"
	xsi:schemaLocation="http://www.eclipse.org/mat/report.xsd platform:/resource/org.eclipse.mat.report/schema/report.xsd">

	<param key="html.collapsed" value="false" />
	<param key="filename_suffix" value="%suspects.suffix" />	

	<section name="%overview.title">
		<param key="html.separate_file" value="true" />
		<template>org.eclipse.mat.api:overview</template>
	</section>
	
	<query name="%suspects.leaks">
		<command>leakhunter</command>
	</query>

</section>

=== eclipse-mat/mat/plugins/org.eclipse.mat.api/META-INF/reports/overview2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (c) 2008, 2020 SAP AG and IBM Corporation.
    All rights reserved. This program and the accompanying materials
    are made available under the terms of the Eclipse Public License v1.0
    which accompanies this distribution, and is available at
    http://www.eclipse.org/legal/epl-v10.html
   
    Contributors:
        SAP AG - initial API and implementation
        Andrew Johnson - comparison queries
 -->
<section name="%overview2.title System Overview comparison" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.eclipse.org/mat/report.xsd" xsi:schemaLocation="http://www.eclipse.org/mat/report.xsd platform:/resource/org.eclipse.mat.report/schema/report.xsd">

	<param key="html.collapsed" value="false" />
	<param key="filename_suffix" value="%overview2.suffix Overview Delta" />

	<query name="%overview.heap_dump_overview">
		<param key="html.show_table_header" value="false" />
		<command>simplecomparison -query heap_dump_overview -baseline ${baseline}</command>
	</query>
	<query name="%overview.system_properties">
		<param key="html.separate_file" value="true" />
		<param key="sort_column" value="#0=ASC" />
		<param key="hide_column" value="#1,#2" />
		<param key="limit" value="1000" />
		<command>simplecomparison -query system_properties -options "-keycolumn 2" -baseline ${baseline}</command>
	</query>
	<query name="%overview.threads">
		<param key="limit" value="1000" />
		<param key="html.separate_file" value="true" />
		<param key="html.render_details" value="false" />
		<command>simplecomparison -query thread_overview -baseline ${baseline}</command>
	</query>
	<query name="%overview.class_histogram">
		<param key="html.separate_file" value="true" />
		<param key="sort_column" value="#6" />
		<command>simplecomparison -query histogram -retained APPROXIMATE -options "-mode DIFF_TO_PREVIOUS" -baseline ${baseline}</command>
	</query>
	<!-- Expensive to calculate, so use version from LeaKHunter2
	<query name="%overview2.dominator_tree Dominator tree">
		<param key="html.separate_file" value="true" />
		<param key="sort_column" value="#5" />
		<param key="hide_column" value="#7,#8,#9" />
		<command>simplecomparison -query dominator_tree -options "-mode DIFF_RATIO_TO_FIRST" -baseline ${baseline}</command>
	</query>
	-->
</section>
